# Generated by Django 4.0.1 on 2022-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteorecord',
            name='record_time',
            field=models.DateTimeField(),
        ),
    ]
