# Generated by Django 4.0.1 on 2022-02-02 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0002_alter_meteorecord_record_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteorecord',
            options={'ordering': ['-DATE']},
        ),
        migrations.RemoveField(
            model_name='meteorecord',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='meteorecord',
            name='record_time',
        ),
        migrations.RemoveField(
            model_name='meteorecord',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='meteorecord',
            name='wind_direction',
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='DATE',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='DP',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='PA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='PR',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='PR1H',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='PR24h',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='RH',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='SD_1D',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='SD_1H',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='SD_45_1D',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='SD_45_1H',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='SR_1D',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='SR_1M',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='SR_45_1D',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='SR_45_1M',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='TA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='WC',
            field=models.FloatField(default=0),
        ),
    ]
