# Generated by Django 4.0.1 on 2022-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0003_alter_meteorecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteorecord',
            name='TA',
            field=models.FloatField(),
        ),
    ]
