# Generated by Django 4.0.1 on 2022-02-08 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0004_alter_meteorecord_ta'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('WS1AVG', models.FloatField(default=0)),
                ('WD1AVG', models.FloatField(default=0)),
                ('WS1MIN2', models.FloatField(default=0)),
                ('WS1AVG2', models.FloatField(default=0)),
                ('WS1MAX2', models.FloatField(default=0)),
                ('WD1MIN2', models.FloatField(default=0)),
                ('WD1AVG2', models.FloatField(default=0)),
                ('WD1MAX2', models.FloatField(default=0)),
                ('WS1MIN10', models.FloatField(default=0)),
                ('WS1AVG10', models.FloatField(default=0)),
                ('WS1MAX10', models.FloatField(default=0)),
                ('WD1MIN10', models.FloatField(default=0)),
                ('WD1AVG10', models.FloatField(default=0)),
                ('WD1MAX10', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-DATE'],
            },
        ),
    ]
